- name: Deploy aws ec2 instance
  hosts: localhost
  collections:
    - amazon.aws
  vars_files:
    - variables.yaml
    - vault-variables.yaml
  tasks:
  - name: Create {{ aws_vpc_name }} VPC
    amazon.aws.ec2_vpc_net:
      name: "{{ aws_vpc_name }}"
      cidr_block: "{{ aws_cidr_block }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      state: present
    register: vpc

  - name: Create Subnet
    amazon.aws.ec2_vpc_subnet:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      cidr: "{{ aws_sub_cidr }}"
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc.vpc.id }}"
      state: present
      map_public: yes
    register: subnet

  - name: Create IGW
    amazon.aws.ec2_vpc_igw:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc.vpc.id }}"
      state: present
    register: igw

  - name: Route IGW
    amazon.aws.ec2_vpc_route_table:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc.vpc.id }}"
      tags:
        Name: PublicWireguard
      subnets:
        - "{{ subnet.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id  }}"

  - name: Create {{ aws_sg_name }} Security Group
    amazon.aws.ec2_security_group:
      name: "{{ aws_sg_name }}"
      description: "Security group for wireguard"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      rules:
        - proto: udp
          ports:
            - 51820
          cidr_ip: 0.0.0.0/0
          rule_desc: "allow all on port 51820"
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: "allow SSH"
    register: security_group

  - name: Search all EC2 instances with name {{ aws_instance_name }} and state running
    amazon.aws.ec2_instance_info:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      aws_region: "{{ aws_region }}"
      filters:
        "tag:Name": "{{ aws_instance_name }}"
        instance-state-name: [ "running"]
    register: wg_ec2_info

  - name: Get latest Amazon Linux 2023 AMI 64-bit (x86)
    amazon.aws.ec2_ami_info:
      owners:
        - amazon
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ aws_region }}"
      filters:
        name: "al2023-ami-*-x86_64"
        architecture: x86_64
        state: available
        virtualization-type: hvm
    register: amazon_linux_2023_amis
    when: aws_image_id is not defined or aws_image_id == ""

  - name: Set aws_image_id to latest Amazon Linux 2023 AMI
    ansible.builtin.set_fact:
      aws_image_id: "{{ (amazon_linux_2023_amis.images | sort(attribute='creation_date', reverse=true) | first).image_id }}"
    when: aws_image_id is not defined or aws_image_id == ""

  - name: Display selected AMI ID
    ansible.builtin.debug:
      msg: "Using AMI ID: {{ aws_image_id }}"

  - name: Launch {{ aws_instance_name }} EC2 Instance
    amazon.aws.ec2_instance:
      name: "{{ aws_instance_name }}"
      key_name: "{{ aws_key_name }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_subnet_id: "{{ subnet.subnet.id }}"
      instance_type: "{{ aws_instance_type }}"
      security_group: "{{ security_group.group_id  }}"
      state: running
      count: 1
      wait: yes
      aws_region: "{{ aws_region }}"
      network_interfaces:
        - subnet_id: "{{ subnet.subnet.id }}"
          delete_on_termination: true
          assign_public_ip: true
      image_id: "{{ aws_image_id }}"
    when:
      - not wg_ec2_info.instances[0] is defined
    register: wg_instance

  - name: Search all EC2 instances with name {{ aws_instance_name }} and state running for writing hosts-aws
    amazon.aws.ec2_instance_info:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      aws_region: "{{ aws_region }}"
      filters:
        "tag:Name": "{{ aws_instance_name }}"
        instance-state-name: [ "running"]
    register: wg_ec2_info

  - name: Write commodity hosts-aws file
    ansible.builtin.copy:
      dest: hosts-aws
      content: |
        [wireguard]
        {{ aws_instance_name }} ansible_ssh_user=ec2-user ansible_ssh_host={{ wg_ec2_info.instances[0].public_ip_address }} ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  - name: Add wireguard group-host
    ansible.builtin.add_host:
      name: "{{ aws_instance_name }}"
      ansible_ssh_user: ec2-user
      ansible_ssh_host: "{{ wg_ec2_info.instances[0].public_ip_address }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '
      groups:
        - wireguard

  - name: Wait for SSH to be ready on EC2 instance
    ansible.builtin.wait_for:
      host: "{{ wg_ec2_info.instances[0].public_ip_address }}"
      port: 22
      delay: 10
      timeout: 300
      state: started
